version: "3.9"

services:
  ocr:
    image: ghaemieh-ocr:11.22.2025.ubuntu
    container_name: ghaemieh-ocr-refactored
    working_dir: /app
    command: python main.py
    ports:
      - "3334:4567"
    env_file:
      - .env
    environment:
      FASTAPI_PORT: 4567
    volumes:
      - ./:/app
